pipeline {
    agent any

    stages {

        stage('Compile') {
            steps {
                dir('cicd') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('cicd') {
                    sh './mvnw test'
                }
            }
        }
        stage('Quality Gate') {
            steps {
                dir('cicd') {
                    sh './mvnw verify -DskipTests'
                  }
              }
          }
        stage('SonarQube Analysis') {
        steps {
              dir('cicd') {
              withSonarQubeEnv('SonarQube') {
              sh './mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:5.7.0.6970:sonar'
              }
            }
          }
        }      
        stage('SonarQube Quality Gate') {
          steps {
            timeout(time: 10, unit: 'MINUTES') {
              waitForQualityGate abortPipeline: true
            }
          }
        }
        stage('Package') {
            when {
              anyOf {
                branch 'dev'
                branch 'main'
              }
            }
            steps {
                dir('cicd') {
                    sh './mvnw package -DskipTests'
                }
            }
        }
        
        stage('Docker Build') {
           when {
            anyOf {
              branch 'dev'
              branch 'main'
            }
          }
          steps {
            dir('cicd') {
               sh 'docker build -t hello-cicd:${BUILD_NUMBER} .'
            }
          }
        }
        stage('Docker Push') {
          when {
            anyOf {
              branch 'dev'
              branch 'main'
            }
          }
        steps {
          withCredentials([
            usernamePassword(
                credentialsId: 'ghcr-credentials',
                usernameVariable: 'GHCR_USER',
                passwordVariable: 'GHCR_TOKEN'
            )
        ]) {
            sh '''
                echo "$GHCR_TOKEN" | docker login ghcr.io -u "$GHCR_USER" --password-stdin

                docker tag hello-cicd:${BUILD_NUMBER} \
                  ghcr.io/biswajeet97/hello-cicd:${BUILD_NUMBER}

                docker push \
                  ghcr.io/biswajeet97/hello-cicd:${BUILD_NUMBER}
            '''
            }
          }
        }
        stage('Deploy DEV') {
        when {
          branch 'dev'
        }

        steps {
          sh '''
            docker pull ghcr.io/biswajeet97/hello-cicd:${BUILD_NUMBER}

            docker stop hello-cicd-dev || true
            docker rm hello-cicd-dev || true

            docker run -d \
              --name hello-cicd-dev \
              --network jenkins_default \
              -p 8081:8080 \
              ghcr.io/biswajeet97/hello-cicd:${BUILD_NUMBER}
            '''
          }
        }

        stage('Smoke Test DEV') {
          when {
          branch 'dev'
        }

        steps {
          sh '''
            sleep 10

            RESPONSE=$(curl -s -o /tmp/response.txt -w "%{http_code}" http://localhost:8081/api/hello)

            if [ "$RESPONSE" != "200" ]; then
                echo "DEV smoke test failed with HTTP status $RESPONSE"
                cat /tmp/response.txt || true
                exit 1
            fi

            grep -q "Hello World" /tmp/response.txt
          '''
        }
      }
    }

    post {
        always {
            junit testResults: 'cicd/target/surefire-reports/*.xml',
                  allowEmptyResults: true
            archiveArtifacts artifacts: 'cicd/target/site/jacoco/**',
                  allowEmptyArchive: true
        }

        success {
            echo 'BUILD SUCCESSFUL'
        }

        failure {
            echo 'BUILD FAILED'
        }
    }
}
