pipeline {
    agent any

    stages {

        stage('Compile') {
            steps {
                dir('cicd') {
                    sh 'chmod +x mvnw'
                    sh './mvnw clean compile'
                }
            }
        }

        stage('Test') {
            steps {
                dir('cicd') {
                    sh './mvnw test'
                }
            }
        }
        stage('Quality Gate') {
            steps {
                dir('cicd') {
                    sh './mvnw verify -DskipTests'
                  }
              }
          }
        stage('Package') {
            steps {
                dir('cicd') {
                    sh './mvnw package -DskipTests'
                }
            }
        }
    }

    post {
        always {
            junit testResults: 'cicd/target/surefire-reports/*.xml',
                  allowEmptyResults: true
            archiveArtifacts artifacts: 'cicd/target/site/jacoco/**',
                  allowEmptyArchive: true
        }

        success {
            echo 'BUILD SUCCESSFUL'
        }

        failure {
            echo 'BUILD FAILED'
        }
    }
}
